CREATE SEQUENCE URLS_ID_SEQ;

CREATE TABLE URLS(
  ID INTEGER NOT NULL DEFAULT nextval('URLS_ID_SEQ'::regclass),
  ORIGINAL_URL VARCHAR(255) not null,
  SHORTEN_URL VARCHAR(255) not null,
  LAST_UPDATE_DATE TIMESTAMP default current_date,
  CONSTRAINT URL_PKEY PRIMARY KEY (ID)
);

ALTER SEQUENCE URLS_ID_SEQ OWNED BY URLS.id;