CREATE SEQUENCE USERS_ID_SEQ;

CREATE TABLE USERS (
  ID INTEGER NOT NULL DEFAULT nextval('USERS_ID_SEQ'::regclass),
  FIRST_NAME CHARACTER VARYING(45) COLLATE pg_catalog."default" NOT NULL,
  LAST_NAME CHARACTER VARYING(45) COLLATE pg_catalog."default" NOT NULL,
  EMAIL CHARACTER VARYING(50) COLLATE pg_catalog."default",
  ACTIVE BOOLEAN NOT NULL DEFAULT true,
  CREATE_DATE DATE NOT NULL DEFAULT ('now'::text)::date,
  LAST_UPDATE TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  CONSTRAINT USER_PKEY PRIMARY KEY (id)
);

ALTER SEQUENCE USERS_ID_SEQ OWNED BY USERS.id;

INSERT INTO public.USERS(FIRST_NAME, LAST_NAME, EMAIL, ACTIVE)
VALUES ('De', 'Kapx', 'dekapx@dvdrental.com', true);

INSERT INTO public.USERS(FIRST_NAME, LAST_NAME, EMAIL, ACTIVE)
VALUES ('Test', 'User', 'testuser@dvdrental.com', true);