insert into STATUS (STATUS) values('AUTHORISED');
insert into STATUS (STATUS) values('PENDING_AUTHORISED');
insert into STATUS (STATUS) values('PENDING_NEW_AUTHORISED');
insert into STATUS (STATUS) values('PENDING_UPDATE_AUTHORISED');